pipeline {
    agent {
        label 'agent'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url:'https://github.com/PriyeshPandey07/bootstrap-website.git', branch: 'main'
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
        	     sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
                }
            }
        }
        stage("build image")
        {
            steps {
                script {
                    sh "docker build -t avengerimg:latest ."
                }
            }
        }
        
        stage("run container")
        {
            steps {
                script {
                    sh "docker-compose up -d"
                }
            }
        }
    }
}
